
$schema: https://json.schemastore.org/github-action.json
# https://github.com/sst/opencode/blob/dev/sdks/github/action.yml
# example usage: https://github.com/sst/opencode/blob/dev/.github/workflows/opencode.yml
name: "BuildMedic"
description: |
  Run your build once and, if it fails, let Claude
  patch the code in‑place, retry (up to max_attempts),
  and open a pull‑request with the fix.

author: "remorses"
branding:
  icon: activity
  color: purple

inputs:
  command:
    description: "Shell commands that must succeed (run as one string)"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.16

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Install opencode
      shell: bash
      run: curl -fsSL https://opencode.ai/install | bash

    - name: Run BuildMedic
      shell: bash
      id: run_buildmedic
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/index.ts
      # env:
      #   INPUT_MODEL: ${{ inputs.model }}
      #   INPUT_SHARE: ${{ inputs.share }}
