name: "Self‑Healing CI"
description: |
  Run your build once and, if it fails, let Claude
  patch the code in‑place, retry (up to max_attempts),
  and open a pull‑request with the fix.

author: "remorses"
branding:
  icon: activity
  color: purple

inputs:
  anthropic_api_key:
    description: "Secret: your Anthropic Claude API key"
    required: true

  commands:
    description: "Shell commands that must succeed (run as one string)"
    default: "npm ci && npm run build"
    required: false

  allowed_tools:
    description: |
      Comma‑separated list of Claude tools allowed.
      Keep minimal for safety; add Bash(gh *) if you want CLAUDE to run gh‑cli.
    default: "Bash(git:*),View,Write"
    required: false

  timeout_minutes:
    description: "Hard time‑out for the Claude session"
    default: "15"
    required: false

  max_turns:
    description: "Max Claude turns (round‑trips) before the action aborts"
    default: "10"
    required: false

  max_attempts:
    description: "Max build / fix iterations before giving up"
    default: "3"
    required: false

runs:
  using: "composite"
  steps:
    - id: self‑heal
      uses: anthropics/claude-code-base-action@beta
      env:
        GH_TOKEN: ${{ env.GH_TOKEN }} # must be set by caller (usually ${{ secrets.GITHUB_TOKEN }})
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        timeout_minutes: ${{ inputs.timeout_minutes }}
        max_turns: ${{ inputs.max_turns }}
        allowed_tools: ${{ inputs.allowed_tools }}

        prompt: |
          You are our CI self‑healing agent.

          **Workflow**
          1. Run the build once:
             ```
             ${{ inputs.commands }}
             ```
          2. If the commands succeed, exit immediately with success—no commits, no PR.
          3. Otherwise, iterate up to **${{ inputs.max_attempts }} attempts**:
             • Diagnose & edit code.
             • `git add -A && git commit -m "fix(build): attempt $ATTEMPT"`.
             • Re‑run `${{ inputs.commands }}`.
          4. After ${{ inputs.max_attempts }} failed attempts, `exit 1` so the job fails.

          **When the build passes**
          1. Create / switch to a branch `claude/fix-build-${GITHUB_RUN_ID}`.
          2. Push and open a PR:
             ```bash
             git push -u origin "$branch"
             gh pr create \
               --base "${{ github.ref_name }}" \
               --title "fix(build): auto‑heal CI" \
               --body  "Automated patch generated by Claude Code 🛠️"
             ```
          Use only the tools listed above.
